# Generated by Django 2.0 on 2018-08-08 02:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig', models.CharField(choices=[('--select--', '--select--'), ('Supervisor', 'Supervisor'), ('TeamLeader', 'TeamLeader'), ('Senior Operator', 'Senior Operator'), ('Skilled Operator', 'Skilled Operator'), ('Semi-Skilled Operator', 'Semi-Skilled Operator'), ('Un-Skilled Operator', 'Un-Skilled Operator'), ('Helper', 'Helper'), ('Trainee', 'Trainee')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=10)),
            ],
        ),
    ]
