# Generated by Django 2.0.7 on 2018-08-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0002_auto_20180809_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='choose',
        ),
        migrations.AddField(
            model_name='employee',
            name='choose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='absenteeism.Lining'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='choosen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='absenteeism.Employee'),
            preserve_default=False,
        ),
    ]
