# Generated by Django 2.0.7 on 2018-08-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0003_auto_20180809_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='choosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absenteeism.Lining'),
        ),
    ]
