# Generated by Django 2.0 on 2018-08-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complx', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Complexity_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complx_fact', models.CharField(choices=[('MF', 'MF'), ('AF', 'AF')], default='MF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30)),
                ('machine', models.CharField(max_length=25)),
                ('automation', models.CharField(choices=[('UBT', 'UBT'), ('Work Aid', 'Work Aid'), ('MT', 'MT')], default='UBT', max_length=20)),
                ('work_Aid', models.CharField(default='BINDER', max_length=50)),
                ('pick_in_sec', models.IntegerField()),
                ('pick_in_frequency', models.IntegerField(default=1)),
                ('main_Process_in_sec', models.IntegerField()),
                ('main_Process_in_frequency', models.IntegerField(default=1)),
                ('turn_in_sec', models.IntegerField()),
                ('turn_in_frequency', models.IntegerField(default=1)),
                ('dispose_in_sec', models.IntegerField()),
                ('dispose_in_frequency', models.IntegerField(default=1)),
                ('personal_Allowance', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('fatigue_Allowance', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('delay_Allowance', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smv.Complexity')),
                ('complexity_Factor', models.ForeignKey(default='MF', on_delete=django.db.models.deletion.CASCADE, to='smv.Complexity_factor')),
            ],
        ),
        migrations.CreateModel(
            name='SPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_p_i', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Stitch_Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitch_length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='smv',
            name='s_P_I',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='smv.SPI'),
        ),
        migrations.AddField(
            model_name='smv',
            name='stitch_Length',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='smv.Stitch_Length'),
        ),
        migrations.AddField(
            model_name='complexity',
            name='complex_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smv.Complexity_factor'),
        ),
    ]
