# Generated by Django 2.0 on 2018-08-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Colar Section', 'Colar Section'), ('Sleeve Section', 'Sleeve Section'), ('Lining Section', 'Lining Section'), ('Front Section', 'Front Section'), ('Assembly Section', 'Assembly Section')], default='Colar Section', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pfm',
            name='sec',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smv.Section'),
        ),
    ]
