# Generated by Django 2.0 on 2018-08-08 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operations', models.CharField(max_length=50)),
                ('opt_weightage', models.IntegerField()),
                ('operation_desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=50)),
                ('skill_desc', models.TextField(max_length=1500)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_matrix.Operat')),
                ('use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
