# Generated by Django 2.0 on 2018-08-08 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absenteeism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('leave_category', models.CharField(choices=[('medical leave', 'medical leave'), ('casual leave', 'casual leave'), ('formal leave', 'formal leave')], max_length=30)),
                ('no_of_days', models.IntegerField(null=True)),
                ('leave_id', models.IntegerField()),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absenteeism.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_percnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_calendar.LeavePercentage'),
        ),
    ]
