# Generated by Django 2.0 on 2018-07-23 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stylemaster', '0003_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shell_fabric', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('lining_fabric', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('trim_fabric', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('fusing', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('trims', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('thread', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('button', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('brand_label', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('fit_label', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('size_label', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('wash_care_label', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('hangtag', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('polybag', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('carton', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('carton_sticket', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('pallet', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('corner_protection', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=15)),
                ('item_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster')),
            ],
        ),
    ]
