# Generated by Django 2.0 on 2018-07-16 11:39

from django.db import migrations, models
import django.db.models.deletion
import stylemaster.models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_no', models.IntegerField(default=stylemaster.models.Fabric.number, unique=True)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('composition', models.CharField(max_length=30)),
                ('weave', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.CharField(blank=True, max_length=5, null=True)),
                ('construction', models.CharField(max_length=10)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_code', models.CharField(choices=[('Fabric00001', 'Fabric00001'), ('Fabric00002', 'Fabric00002')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_no', models.IntegerField(default=stylemaster.models.Trims.number, unique=True)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('composition', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('construction', models.CharField(max_length=10)),
                ('types', models.CharField(blank=True, max_length=50, null=True)),
                ('trim_code', models.CharField(choices=[('Trim00001', 'Trim00001'), ('Trim00002', 'Trim00002')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_no',
            field=models.IntegerField(default=stylemaster.models.Sample.number, unique=True),
        ),
        migrations.AddField(
            model_name='stylemaster',
            name='style_no',
            field=models.IntegerField(default=stylemaster.models.Stylemaster.number, unique=True),
        ),
        migrations.AddField(
            model_name='trims',
            name='trim_item_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='fabric_item_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster'),
        ),
    ]
