# Generated by Django 2.0 on 2018-07-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylemaster', '0002_auto_20180716_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabconsumption', models.CharField(max_length=20)),
                ('fabquality', models.CharField(max_length=20)),
                ('fabwidth', models.CharField(max_length=10)),
                ('fabunit', models.CharField(max_length=5)),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fabrate', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fabcost', models.DecimalField(decimal_places=0, max_digits=3)),
                ('trims', models.CharField(max_length=20)),
                ('trimquality', models.CharField(max_length=20)),
                ('trimspecific', models.CharField(max_length=10)),
                ('trimunit', models.CharField(max_length=5)),
                ('trimconsumption', models.DecimalField(decimal_places=0, max_digits=3)),
                ('trimrate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('trimcost', models.DecimalField(decimal_places=1, max_digits=2)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster')),
            ],
        ),
    ]
