# Generated by Django 2.0 on 2018-07-25 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylemaster', '0003_bom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=50)),
                ('buyer_style', models.IntegerField()),
                ('buyer_p_o', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=50)),
                ('p_o_date', models.DateField(default=datetime.date.today)),
                ('c_o_number', models.IntegerField()),
                ('c_o_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('inv_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ex_factory', models.DateField()),
                ('delivery_method', models.CharField(max_length=15)),
                ('delivery_terms', models.CharField(max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
                ('l_s', models.IntegerField()),
                ('h_s', models.IntegerField()),
                ('c_o_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylemaster.Stylemaster')),
            ],
        ),
    ]
