# Generated by Django 2.0 on 2018-07-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylemaster', '0004_styleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(max_length=15)),
                ('cost_Grp', models.CharField(max_length=15)),
                ('item_Type', models.CharField(max_length=30)),
                ('item_Grp', models.CharField(max_length=30)),
                ('product_grp', models.CharField(max_length=30)),
                ('material_Code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=70)),
                ('budget', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.CharField(choices=[('INR', 'INR'), ('$', '$')], max_length=20)),
                ('UOM', models.CharField(choices=[('MTR', 'MTR'), ('PCS', 'PCS')], max_length=20)),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=12)),
                ('waste', models.DecimalField(decimal_places=3, max_digits=8)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
